services:
  server:
    build: ./server
    depends_on:
      - cache
      - db
    environment:
      - CACHE_ADDR=cache:3124
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=password
      - JWT_KEY=randomstring
    restart: unless-stopped

  cache:
    build: ./cache
    depends_on:
      - db
    environment:
      - PORT=3124
    restart: unless-stopped
    
  db:
    image: postgres:alpine3.15
    environment:
      - POSTGRES_PASSWORD=password

    ports:
      - "5432:5432"
    restart: unless-stopped
    
  nginx:
    image: nginx
    depends_on:
      - server
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./front/banana-notes/build:/usr/share/nginx/html
    ports:
      - "80:80"   
    restart: unless-stopped
     